-- ======================================================
-- 효주T의 수학교실 - Supabase 퀴즈 점수 테이블 생성 쿼리
-- Supabase 대시보드 -> SQL Editor에 복사하여 실행하세요.
-- ======================================================

-- 1. quiz_scores 테이블 생성
CREATE TABLE IF NOT EXISTS public.quiz_scores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id TEXT NOT NULL,
  name TEXT NOT NULL,
  score INT NOT NULL,
  correct_count INT NOT NULL,
  total_questions INT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Row Level Security (RLS) 활성화
ALTER TABLE public.quiz_scores ENABLE ROW LEVEL SECURITY;

-- 3. 익명 및 누구나 읽기 허용 정책 (랭킹 조회용)
CREATE POLICY "Allow public read access" 
  ON public.quiz_scores 
  FOR SELECT 
  USING (true);

-- 4. 누구나 점수 등록 허용 정책 (퀴즈 결과 제출용)
CREATE POLICY "Allow public insert access" 
  ON public.quiz_scores 
  FOR INSERT 
  WITH CHECK (true);
